package com.example.model

data class Weapon(
    val id: String,
    val name: String,
    val category: String, // "Assault Rifle", "SMG", "Shotgun", "Sniper", "Pistol"
    val headshotDamage: Int,
    val bodyDamage: Int,
    val rateOfFire: Int, // 0-100
    val range: Int, // 0-100
    val reloadSpeed: Int, // 0-100
    val magazine: Int,
    val accuracy: Int, // 0-100
    val recoilPattern: String,
    val recoilDescription: String,
    val optimalRange: String,
    val recommendedDrill: String,
    val dragSpeed: String,
    val dragType: String // "STRAIGHT_UP", "J_DRAG", "REVERSE_J", "QUICK_FLICK"
)

object WeaponCatalog {
    val weapons: List<Weapon> = listOf(
        // Assault Rifles
        Weapon(
            id = "ak47",
            name = "AK47",
            category = "Assault Rifle",
            headshotDamage = 205,
            bodyDamage = 38,
            rateOfFire = 55,
            range = 73,
            reloadSpeed = 41,
            magazine = 30,
            accuracy = 42,
            recoilPattern = "High vertical bloom after shot 3. Requires smooth downward counter after initial drag.",
            recoilDescription = "Start drag high then hold steady. 2-3 tap bursts guarantee headshots without bullet spread bloom.",
            optimalRange = "Mid to Long Range (20m - 50m)",
            recommendedDrill = "Headshot Drill",
            dragSpeed = "Medium-Fast upward swipe",
            dragType = "STRAIGHT_UP"
        ),
        Weapon(
            id = "m4a1",
            name = "M4A1",
            category = "Assault Rifle",
            headshotDamage = 168,
            bodyDamage = 29,
            rateOfFire = 57,
            range = 79,
            reloadSpeed = 48,
            magazine = 30,
            accuracy = 55,
            recoilPattern = "Low, highly predictable vertical climb. Extremely stable across long sprays.",
            recoilDescription = "Easiest AR for beginners. Straight upward drag from mid chest to head level.",
            optimalRange = "Mid Range (15m - 40m)",
            recommendedDrill = "Tracking Drill",
            dragSpeed = "Smooth steady pull",
            dragType = "STRAIGHT_UP"
        ),
        Weapon(
            id = "scar",
            name = "SCAR",
            category = "Assault Rifle",
            headshotDamage = 175,
            bodyDamage = 33,
            rateOfFire = 61,
            range = 68,
            reloadSpeed = 52,
            magazine = 30,
            accuracy = 50,
            recoilPattern = "Stable fire rate allows consistent drag headshots during mid-range duels.",
            recoilDescription = "Consistent rate of fire makes rhythm easy to master. Combine with jump-shot drag.",
            optimalRange = "Mid Range (15m - 35m)",
            recommendedDrill = "Accuracy Test",
            dragSpeed = "Medium pace upward drag",
            dragType = "STRAIGHT_UP"
        ),
        Weapon(
            id = "woodpecker",
            name = "Woodpecker",
            category = "Assault Rifle",
            headshotDamage = 312,
            bodyDamage = 72,
            rateOfFire = 38,
            range = 63,
            reloadSpeed = 48,
            magazine = 12,
            accuracy = 69,
            recoilPattern = "DMR single-shot recoil bounce. High armor penetration.",
            recoilDescription = "The ultimate one-tap DMR. Single rapid flick upward directly to the enemy's head level.",
            optimalRange = "Mid to Long Range (25m - 60m)",
            recommendedDrill = "Flick Drill",
            dragSpeed = "Fast explosive snap",
            dragType = "QUICK_FLICK"
        ),

        // SMGs
        Weapon(
            id = "mp40",
            name = "MP40",
            category = "SMG",
            headshotDamage = 135,
            bodyDamage = 24,
            rateOfFire = 83,
            range = 22,
            reloadSpeed = 48,
            magazine = 20,
            accuracy = 17,
            recoilPattern = "Rapid upward recoil bloom within 0.8s of firing. Must lock headshot within first 5 bullets.",
            recoilDescription = "Fastest close-range drag weapon. Use 'J-Drag' technique if enemy is strafing sideways.",
            optimalRange = "Close Range (2m - 12m)",
            recommendedDrill = "Headshot Drill",
            dragSpeed = "Hyper-fast upward swipe",
            dragType = "J_DRAG"
        ),
        Weapon(
            id = "ump",
            name = "UMP",
            category = "SMG",
            headshotDamage = 158,
            bodyDamage = 31,
            rateOfFire = 75,
            range = 24,
            reloadSpeed = 59,
            magazine = 30,
            accuracy = 42,
            recoilPattern = "Built-in armor penetration. Bullet spread is narrow and forgiving.",
            recoilDescription = "King of tournament SMGs. Rotation drag allows connecting headshots even when aiming at waist.",
            optimalRange = "Close to Mid Range (5m - 20m)",
            recommendedDrill = "Tracking Drill",
            dragSpeed = "Fast curved drag",
            dragType = "J_DRAG"
        ),
        Weapon(
            id = "mp5",
            name = "MP5-X",
            category = "SMG",
            headshotDamage = 145,
            bodyDamage = 26,
            rateOfFire = 76,
            range = 27,
            reloadSpeed = 62,
            magazine = 30,
            accuracy = 53,
            recoilPattern = "Equipped with electrical booster chip. Near laser accuracy in burst sprays.",
            recoilDescription = "Gentle upward pressure required. Very forgiving crosshair spread.",
            optimalRange = "Close to Mid Range (8m - 25m)",
            recommendedDrill = "Accuracy Test",
            dragSpeed = "Smooth medium drag",
            dragType = "STRAIGHT_UP"
        ),

        // Shotguns
        Weapon(
            id = "m1887",
            name = "M1887",
            category = "Shotgun",
            headshotDamage = 520,
            bodyDamage = 100,
            rateOfFire = 40,
            range = 14,
            reloadSpeed = 55,
            magazine = 2,
            accuracy = 10,
            recoilPattern = "Extreme single-blast pellet spread. Massive recoil kick per shot.",
            recoilDescription = "Requires instant 1-tap jump shot. Flick fire button in an explosive curve toward the head.",
            optimalRange = "Point Blank to Close (1m - 8m)",
            recommendedDrill = "Reaction Drill",
            dragSpeed = "Maximum explosive flick",
            dragType = "J_DRAG"
        ),
        Weapon(
            id = "m1014",
            name = "M1014",
            category = "Shotgun",
            headshotDamage = 450,
            bodyDamage = 94,
            rateOfFire = 38,
            range = 10,
            reloadSpeed = 32,
            magazine = 6,
            accuracy = 10,
            recoilPattern = "Continuous pump recoil. Crosshair resets between shots.",
            recoilDescription = "Timing rhythm is key. Pull trigger at peak of jump when crosshair aligns with opponent's neck.",
            optimalRange = "Point Blank (1m - 6m)",
            recommendedDrill = "Reaction Drill",
            dragSpeed = "Sharp rhythmic pull",
            dragType = "QUICK_FLICK"
        ),
        Weapon(
            id = "mag7",
            name = "MAG-7",
            category = "Shotgun",
            headshotDamage = 380,
            bodyDamage = 84,
            rateOfFire = 53,
            range = 15,
            reloadSpeed = 55,
            magazine = 8,
            accuracy = 17,
            recoilPattern = "Fast auto-shotgun. High rate of fire with tight initial grouping.",
            recoilDescription = "Hold fire and track opponent smoothly upwards. High survivability in rush fights.",
            optimalRange = "Close Range (2m - 10m)",
            recommendedDrill = "Tracking Drill",
            dragSpeed = "Continuous medium pull",
            dragType = "STRAIGHT_UP"
        ),

        // Snipers
        Weapon(
            id = "awm",
            name = "AWM",
            category = "Sniper",
            headshotDamage = 1100,
            bodyDamage = 150,
            rateOfFire = 27,
            range = 91,
            reloadSpeed = 34,
            magazine = 5,
            accuracy = 90,
            recoilPattern = "Severe bolt-action recoil. Requires quick-switch cancellation to shoot rapidly.",
            recoilDescription = "Quick scope technique: Tap scope -> align -> fire -> quick weapon switch to bypass bolt animation.",
            optimalRange = "Long Range (30m - 100m+)",
            recommendedDrill = "Flick Drill",
            dragSpeed = "Instant pinpoint flick",
            dragType = "QUICK_FLICK"
        ),
        Weapon(
            id = "m82b",
            name = "M82B",
            category = "Sniper",
            headshotDamage = 950,
            bodyDamage = 125,
            rateOfFire = 27,
            range = 85,
            reloadSpeed = 32,
            magazine = 8,
            accuracy = 90,
            recoilPattern = "Armor-piercing & gloo wall penetration. Hits behind ice walls.",
            recoilDescription = "Aim directly through gloo wall silhouette markings. Keep crosshair at standing head height.",
            optimalRange = "Long Range (25m - 90m)",
            recommendedDrill = "Reaction Drill",
            dragSpeed = "Steady scope snap",
            dragType = "QUICK_FLICK"
        ),

        // Pistols
        Weapon(
            id = "desert_eagle",
            name = "Desert Eagle",
            category = "Pistol",
            headshotDamage = 495,
            bodyDamage = 90,
            rateOfFire = 33,
            range = 38,
            reloadSpeed = 69,
            magazine = 7,
            accuracy = 45,
            recoilPattern = "Clash Squad one-tap staple. Single heavy upward kick.",
            recoilDescription = "The legendary one-tap pistol. Drag fire button up and slightly to the right for instant 495 headshot.",
            optimalRange = "Close to Mid Range (5m - 25m)",
            recommendedDrill = "Headshot Drill",
            dragSpeed = "Sharp instant snap",
            dragType = "J_DRAG"
        ),
        Weapon(
            id = "m500",
            name = "M500",
            category = "Pistol",
            headshotDamage = 247,
            bodyDamage = 45,
            rateOfFire = 35,
            range = 76,
            reloadSpeed = 69,
            magazine = 5,
            accuracy = 10,
            recoilPattern = "Built-in 2x scope. High one-tap headshot multiplier in early round CS.",
            recoilDescription = "Keep default crosshair red before initiating upward swipe. Requires clean release.",
            optimalRange = "Mid to Long Range (15m - 40m)",
            recommendedDrill = "Accuracy Test",
            dragSpeed = "Clean vertical release",
            dragType = "STRAIGHT_UP"
        )
    )
}
